repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.88.4
    hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_validate
    - id: terraform_docs
      args:
      - --args=--output-file README.md
      - --args=--output-file /module/cluster/README.md
      - --args=--output-file /module/network/README.md
      - --args=--output-file /module/aws-load-balancer-controller/README.md
      - --args=--output-file /module/managed-node-group/README.md